# RANDOM SEED
RAND_SEED = 123

# MODEL PARAMETERS
N_EPOCHS = 1000
BATCH_SIZE = 12
HIDDEN_UNITS = [20, 10, 1]

# AVAILABLE MODEL MODES
# USE_PRE_TRAINED: LOAD PREVIOUSLY SAVED MODELS, NO NEW TRAINING
# RESUME_TRAINING: LOAD PREVIOUSLY SAVED MODELS, AND RESUME TRAINING
# RESET_MODEL: RESTART TRAINING FROM SCRATCH
MODEL_MODE = 'USE_PRE_TRAINED'
FILL_DATA = True
RESCALE_DATA = False

# DATASET PARAMETERS
FEATURE_COLUMNS = [True, True, True, True, True, True, True, True, False]
PORTION_TEST = 0.3
PORTION_VALID = 0.2
